#!/bin/bash

set -uex

install-packages \
    jenkins \
    jenkins-client \
    openshift-origin-cartridge-jenkins \
    openshift-origin-cartridge-mariadb \
    openshift-origin-cartridge-10gen-mms-agent \
    openshift-origin-cartridge-cron \
    openshift-origin-cartridge-diy \
    openshift-origin-cartridge-haproxy \
    openshift-origin-cartridge-mongodb \
    openshift-origin-cartridge-nodejs \
    openshift-origin-cartridge-perl \
    openshift-origin-cartridge-php \
    openshift-origin-cartridge-phpmyadmin \
    openshift-origin-cartridge-postgresql \
    openshift-origin-cartridge-python \
    openshift-origin-cartridge-ruby \
    openshift-origin-cartridge-jenkins-client \
    mcollective \
    rubygem-openshift-origin-node \
    rubygem-passenger-native \
    openshift-origin-node-util \
    policycoreutils-python \
    openshift-origin-msg-node-mcollective \
    git \
    make \
    oddjob \
    vim-enhanced \
    policycoreutils \
    httpd \
    openssh-server \
    rhc \
    ntpdate \
    pam_openshift \
    rubygem-openshift-origin-container-selinux \
    httpd \
    rubygem-openshift-origin-frontend-apache-mod-rewrite \
    openshift-origin-node-proxy \
    rubygem-openshift-origin-frontend-nodejs-websocket \
    cronie \
    puppet \
    system-config-firewall-base \
    autogen-libopts \
    ntp \
    libogg \
    libvorbis \
    flac \
    tzdata-java \
    wget \
    libasyncns \
    gsm \
    libsndfile \
    pulseaudio-libs \
    jline \
    rhino \
    ttmkfdir \
    xorg-x11-fonts-Type1 \
    1java-1.7.0-openjdk \
    jenkins \
    jenkins-plugin-openshift

sed --in-place -e s/Type=oneshot/"Type=oneshot\nTimeoutSec=0"/ /lib/systemd/system/cloud-final.service

cat <<EOF > /root/configure_origin.pp
class { 'openshift_origin' :
  roles                      => ['node'],
  install_method             => 'none',
  domain                     => 'example.com',
  broker_hostname            => 'broker.example.com',
  named_hostname             => 'broker.example.com',
  datastore_hostname         => 'broker.example.com',
  activemq_hostname          => 'broker.example.com',
  node_hostname              => 'node1.example.com',
  broker_ip_addr             => '',
  named_ip_addr              => '',
  bind_key                   => 'u0MUGq/dgmLi9FAqS8Wiu5MkpjCmrchLeteu17BP/IcSmh9M8Z6vE9mzvsoZaPGYU90BwlmKT8cAAkRezLnE0g==',
  development_mode           => true,
  register_host_with_named   => true,
  node_unmanaged_users       => ['fedora'],
  firewall_provider          => 'lokkit',
}
EOF

