#!/bin/bash

set -uex

yum clean all
yum -y update

install-packages \
  activemq \
  activemq-client \
  openshift-origin-broker \
  openshift-origin-broker-util \
  rubygem-openshift-origin-msg-broker-mcollective \
  rubygem-openshift-origin-dns-nsupdate \
  rhc \
  openshift-origin-console \
  iptables \
  iptables-services \
  system-config-firewall-base \
  mcollective-client \
  mongodb \
  mongodb-server \
  bind \
  bind-utils \
  rubygem-openshift-origin-auth-remote-user \
  pam_openshift \
  rubygem-openshift-origin-dns-nsupdate \
  httpd \
  openssh \
  mongodb \
  mongodb-server \
  ntpdate \
  policycoreutils \
  openssh-server \
  puppet \
  tar \
  yum-plugin-priorities \
  ntp \
  wget \
  unzip \
  vim \
  mlocate

sed --in-place -e s/Type=oneshot/"Type=oneshot\nTimeoutSec=0"/ /lib/systemd/system/cloud-final.service

